apiVersion: v1
kind: Service
metadata:
  name: prometheus-tks-{{ include "node-local-dns.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "9353"
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9353
      targetPort: 9353
  selector:
    k8s-app: {{ include "node-local-dns.fullname" . }}
